"""
db/all_models.py — imports every ORM model for its registration side-effect.

Why this exists: SQLAlchemy resolves `relationship("Workspace")`-style string
targets lazily, at first mapper configuration. A process that imports only SOME
models therefore blows up on the first query with

    InvalidRequestError: When initializing mapper Mapper[Workflow(workflows)],
    expression 'Workspace' failed to locate a name ('Workspace')

The FastAPI app never hits this because including its routers transitively
imports every module. The Celery worker does: `celery -A src.workers.celery_app`
imports only the task modules named in `include`, which reach
executions/workflows models but not workspaces, auth, audit_logs or tools — all
of which are relationship targets from those two.

Import this module (not individual models) from any entry point that is not the
FastAPI app. It is import-only; it exports nothing.

NOTE: alembic/env.py keeps its own copy of this list, deliberately — it needs the
imports before it touches `Base.metadata`, and it is the one place where an
accidental omission shows up immediately as a missing table in an autogenerated
migration. If you add a module, add it in both places.
"""

# ruff: noqa: F401

from src.db.base import Base
from src.modules.agents.models import Agent, AgentMemory, AgentSession, AgentVersion
from src.modules.audit_logs.models import AuditLog
from src.modules.auth.models import OrgMembership, Role, User
from src.modules.billing.models import BillingAccount, BillingUsageRecord
from src.modules.chat.models import Chat, Message
from src.modules.executions.models import NodeExecution, WorkflowRun
from src.modules.integrations.models import Integration
from src.modules.knowledge_base.models import Document, DocumentChunk, KnowledgeBase, OCRResult
from src.modules.notifications.models import Notification
from src.modules.organizations.models import APIKey, Organization
from src.modules.prompts.models import Prompt, PromptVersion
from src.modules.settings.models import Setting
from src.modules.tools.models import Tool, ToolExecution
from src.modules.webhooks.models import Webhook
from src.modules.workflows.models import Workflow, WorkflowEdge, WorkflowNode, WorkflowVersion
from src.modules.workspaces.models import Workspace
